const Map<String, String> authStringsEn = {
  'auth.login.title': 'Log In',
  'auth.login.welcome': 'Welcome',
  'auth.login.description':
      'Log in to continue tracking your fitness journey with FitBody.',
  'auth.login.emailLabel': 'Username or email',
  'auth.login.emailRequired': 'Please enter your email',
  'auth.login.passwordLabel': 'Password',
  'auth.login.passwordRequired': 'Please enter your password',
  'auth.login.forgotPassword': 'Forgot Password?',
  'auth.login.submit': 'Log In',
  'auth.login.noAccount': "Don't have an account? ",
  'auth.login.signUp': 'Sign Up',
  'auth.login.success': 'Logged in successfully',
  'auth.login.failure': 'Login failed',

  'auth.register.title': 'Create Account',
  'auth.register.heading': "Let's Start!",
  'auth.register.fullNameLabel': 'Full name',
  'auth.register.fullNameHint': 'John Doe',
  'auth.register.fullNameRequired': 'Please enter your full name',
  'auth.register.emailLabel': 'Email or Mobile Number',
  'auth.register.emailRequired': 'Please enter your email',
  'auth.register.passwordLabel': 'Password',
  'auth.register.passwordTooShort': 'Password must be at least 8 characters',
  'auth.register.confirmPasswordLabel': 'Confirm Password',
  'auth.register.confirmPasswordMismatch': 'Passwords do not match',
  'auth.register.termsPrefix': 'By continuing, you agree to\n',
  'auth.register.termsOfUse': 'Terms of Use',
  'auth.register.and': ' and ',
  'auth.register.privacyPolicy': 'Privacy Policy',
  'auth.register.periodSuffix': '.',
  'auth.register.submit': 'Sign Up',
  'auth.register.haveAccount': 'Already have an account? ',
  'auth.register.login': 'Log in',
  'auth.register.success': 'Account created successfully',
  'auth.register.failure': 'Registration failed',

  'auth.social.orContinueWith': 'or continue with',

  'auth.forgotPassword.title': 'Forgotten Password',
  'auth.forgotPassword.heading': 'Forgot Password?',
  'auth.forgotPassword.description':
      "Enter the email address associated with your account and we'll send you a verification code.",
  'auth.forgotPassword.emailLabel': 'Enter your email address',
  'auth.forgotPassword.submit': 'Continue',
  'auth.forgotPassword.codeSent': 'A verification code has been sent to your email',
  'auth.forgotPassword.failure': 'Failed to send verification code',

  'auth.verifyCode.title': 'Verification Code',
  'auth.verifyCode.heading': 'Check Your Email',
  'auth.verifyCode.description':
      "We've sent a 6-digit code to {email}. The code is valid for 1 minute.",
  'auth.verifyCode.codeLabel': 'Verification code',
  'auth.verifyCode.codeRequired': 'Please enter all 6 digits',
  'auth.verifyCode.submit': 'Continue',
  'auth.verifyCode.resendIn': 'Resend code in 0:{seconds}',
  'auth.verifyCode.resend': 'Resend code',
  'auth.verifyCode.resendSuccess': 'Verification code resent',
  'auth.verifyCode.resendFailure': 'Failed to resend code',
  'auth.verifyCode.verifySuccess': 'Code verified successfully',
  'auth.verifyCode.verifyFailure': 'Invalid or expired verification code',

  'auth.setPassword.title': 'Set Password',
  'auth.setPassword.description': 'Create a new password for your account.',
  'auth.setPassword.submit': 'Reset Password',
  'auth.setPassword.success': 'Password reset successfully, please log in again',
  'auth.setPassword.failure': 'Failed to reset password',

  'auth.fingerprint.title': 'Set Your Fingerprint',
  'auth.fingerprint.description':
      'Use your fingerprint to sign in faster and more securely next time.',
};

const Map<String, String> authStringsVi = {
  'auth.login.title': 'Đăng nhập',
  'auth.login.welcome': 'Chào mừng',
  'auth.login.description':
      'Đăng nhập để tiếp tục theo dõi hành trình luyện tập của bạn cùng FitBody.',
  'auth.login.emailLabel': 'Tên đăng nhập hoặc email',
  'auth.login.emailRequired': 'Vui lòng nhập email',
  'auth.login.passwordLabel': 'Mật khẩu',
  'auth.login.passwordRequired': 'Vui lòng nhập mật khẩu',
  'auth.login.forgotPassword': 'Quên mật khẩu?',
  'auth.login.submit': 'Đăng nhập',
  'auth.login.noAccount': 'Chưa có tài khoản? ',
  'auth.login.signUp': 'Đăng ký',
  'auth.login.success': 'Đăng nhập thành công',
  'auth.login.failure': 'Đăng nhập thất bại',

  'auth.register.title': 'Tạo tài khoản',
  'auth.register.heading': 'Bắt đầu thôi!',
  'auth.register.fullNameLabel': 'Họ và tên',
  'auth.register.fullNameHint': 'Nguyễn Văn A',
  'auth.register.fullNameRequired': 'Vui lòng nhập họ tên',
  'auth.register.emailLabel': 'Email hoặc số điện thoại',
  'auth.register.emailRequired': 'Vui lòng nhập email',
  'auth.register.passwordLabel': 'Mật khẩu',
  'auth.register.passwordTooShort': 'Mật khẩu tối thiểu 8 ký tự',
  'auth.register.confirmPasswordLabel': 'Xác nhận mật khẩu',
  'auth.register.confirmPasswordMismatch': 'Mật khẩu xác nhận không khớp',
  'auth.register.termsPrefix': 'Khi tiếp tục, bạn đồng ý với\n',
  'auth.register.termsOfUse': 'Điều khoản sử dụng',
  'auth.register.and': ' và ',
  'auth.register.privacyPolicy': 'Chính sách bảo mật',
  'auth.register.periodSuffix': '.',
  'auth.register.submit': 'Đăng ký',
  'auth.register.haveAccount': 'Đã có tài khoản? ',
  'auth.register.login': 'Đăng nhập',
  'auth.register.success': 'Đăng ký thành công',
  'auth.register.failure': 'Đăng ký thất bại',

  'auth.social.orContinueWith': 'hoặc tiếp tục với',

  'auth.forgotPassword.title': 'Quên mật khẩu',
  'auth.forgotPassword.heading': 'Quên mật khẩu?',
  'auth.forgotPassword.description':
      'Nhập địa chỉ email liên kết với tài khoản của bạn, chúng tôi sẽ gửi mã xác nhận.',
  'auth.forgotPassword.emailLabel': 'Nhập địa chỉ email của bạn',
  'auth.forgotPassword.submit': 'Tiếp tục',
  'auth.forgotPassword.codeSent': 'Mã xác nhận đã được gửi tới email của bạn',
  'auth.forgotPassword.failure': 'Gửi mã xác nhận thất bại',

  'auth.verifyCode.title': 'Mã xác nhận',
  'auth.verifyCode.heading': 'Kiểm tra email của bạn',
  'auth.verifyCode.description':
      'Chúng tôi đã gửi mã xác nhận gồm 6 chữ số tới {email}. Mã có hiệu lực trong 1 phút.',
  'auth.verifyCode.codeLabel': 'Mã xác nhận',
  'auth.verifyCode.codeRequired': 'Nhập đủ 6 chữ số',
  'auth.verifyCode.submit': 'Tiếp tục',
  'auth.verifyCode.resendIn': 'Gửi lại mã sau 0:{seconds}',
  'auth.verifyCode.resend': 'Gửi lại mã xác nhận',
  'auth.verifyCode.resendSuccess': 'Đã gửi lại mã xác nhận',
  'auth.verifyCode.resendFailure': 'Gửi lại mã thất bại',
  'auth.verifyCode.verifySuccess': 'Xác nhận mã thành công',
  'auth.verifyCode.verifyFailure': 'Mã xác nhận không đúng hoặc đã hết hạn',

  'auth.setPassword.title': 'Đặt mật khẩu mới',
  'auth.setPassword.description': 'Tạo mật khẩu mới cho tài khoản của bạn.',
  'auth.setPassword.submit': 'Đặt lại mật khẩu',
  'auth.setPassword.success': 'Đặt lại mật khẩu thành công, hãy đăng nhập lại',
  'auth.setPassword.failure': 'Đặt lại mật khẩu thất bại',

  'auth.fingerprint.title': 'Thiết lập vân tay',
  'auth.fingerprint.description':
      'Sử dụng vân tay để đăng nhập nhanh và an toàn hơn trong lần sau.',
};
