const Map<String, String> commonStringsEn = {
  'common.error.generic': 'Something went wrong',
  'common.error.loadFailed': 'Failed to load data: {error}',
  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.retry': 'Retry',
  'common.loading': 'Loading...',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.skip': 'Skip',
  'common.continue': 'Continue',
  'common.search': 'Search',
  'common.noData': 'No data',
};

const Map<String, String> commonStringsVi = {
  'common.error.generic': 'Đã có lỗi xảy ra',
  'common.error.loadFailed': 'Lỗi tải dữ liệu: {error}',
  'common.ok': 'Đồng ý',
  'common.cancel': 'Hủy',
  'common.save': 'Lưu',
  'common.retry': 'Thử lại',
  'common.loading': 'Đang tải...',
  'common.delete': 'Xóa',
  'common.edit': 'Sửa',
  'common.close': 'Đóng',
  'common.confirm': 'Xác nhận',
  'common.back': 'Quay lại',
  'common.next': 'Tiếp theo',
  'common.skip': 'Bỏ qua',
  'common.continue': 'Tiếp tục',
  'common.search': 'Tìm kiếm',
  'common.noData': 'Không có dữ liệu',
};
