const Map<String, String> profileStringsEn = {
  'profile.myProfile': 'My Profile',
  'profile.birthday': 'Birthday: {date}',
  'profile.stats.weight': 'Weight',
  'profile.stats.age': 'Age',
  'profile.stats.height': 'Height',
  'profile.stats.weightValue': '{value} Kg',
  'profile.stats.ageValue': '{value} Years Old',
  'profile.stats.heightValue': '{value} CM',
  'profile.menu.profile': 'Profile',
  'profile.menu.favorite': 'Favorite',
  'profile.menu.privacyPolicy': 'Privacy Policy',
  'profile.menu.settings': 'Settings',
  'profile.menu.help': 'Help',
  'profile.menu.logout': 'Logout',
  'profile.logout.confirm': 'Are you sure you want to log out?',
  'profile.logout.yes': 'Yes, logout',
  'profile.edit.fullName': 'Full name',
  'profile.edit.email': 'Email',
  'profile.edit.mobile': 'Mobile Number',
  'profile.edit.dateOfBirth': 'Date of birth',
  'profile.edit.weight': 'Weight',
  'profile.edit.height': 'Height',
  'profile.edit.submit': 'Update Profile',
  'profile.edit.success': 'Profile updated successfully',
  'profile.edit.failure': 'Failed to update profile',
  'profile.favorites.title': 'Favorites',
  'profile.favorites.all': 'All',
  'profile.favorites.video': 'Video',
  'profile.favorites.article': 'Article',
  'profile.favorites.exercises': '{count} Exercises',
  'profile.privacyPolicy.body':
      'We respect your privacy and are committed to protecting your personal data. This placeholder describes how your information is collected, used and safeguarded while you use FitBody. For the full policy, please contact our support team.',
  'profile.settings.title': 'Settings',
  'profile.settings.notification': 'Notification Setting',
  'profile.settings.password': 'Password Setting',
  'profile.settings.deleteAccount': 'Delete Account',
  'profile.settings.deleteConfirm': 'Are you sure you want to delete your account? This action cannot be undone.',
  'profile.settings.deleteYes': 'Yes, delete',
  'profile.notification.general': 'General Notification',
  'profile.notification.sound': 'Sound',
  'profile.notification.doNotDisturb': "Don't Disturb Mode",
  'profile.notification.vibrate': 'Vibrate',
  'profile.notification.lockScreen': 'Lock Screen',
  'profile.notification.reminders': 'Reminders',
  'profile.password.current': 'Current Password',
  'profile.password.new': 'New Password',
  'profile.password.confirm': 'Confirm New Password',
  'profile.password.forgot': 'Forgot Password?',
  'profile.password.change': 'Change Password',
  'profile.password.required': 'This field is required',
  'profile.password.tooShort': 'Password must be at least 6 characters',
  'profile.password.mismatch': 'New password and confirmation do not match',
  'profile.password.success': 'Password changed successfully',
  'profile.password.failure': 'Failed to change password',
  'profile.help.title': 'Help & FAQs',
  'profile.help.faqTab': 'FAQ',
  'profile.help.contactTab': 'Contact Us',
  'profile.help.general': 'General',
  'profile.help.account': 'Account',
  'profile.help.services': 'Services',
  'profile.help.customerService': 'Customer service',
  'profile.help.website': 'Website',
  'profile.help.whatsapp': 'Whatsapp',
  'profile.help.facebook': 'Facebook',
  'profile.help.instagram': 'Instagram',
};

const Map<String, String> profileStringsVi = {
  'profile.myProfile': 'Hồ Sơ Của Tôi',
  'profile.birthday': 'Sinh nhật: {date}',
  'profile.stats.weight': 'Cân nặng',
  'profile.stats.age': 'Tuổi',
  'profile.stats.height': 'Chiều cao',
  'profile.stats.weightValue': '{value} Kg',
  'profile.stats.ageValue': '{value} Tuổi',
  'profile.stats.heightValue': '{value} CM',
  'profile.menu.profile': 'Hồ sơ',
  'profile.menu.favorite': 'Yêu thích',
  'profile.menu.privacyPolicy': 'Chính sách bảo mật',
  'profile.menu.settings': 'Cài đặt',
  'profile.menu.help': 'Trợ giúp',
  'profile.menu.logout': 'Đăng xuất',
  'profile.logout.confirm': 'Bạn có chắc chắn muốn đăng xuất không?',
  'profile.logout.yes': 'Đồng ý, đăng xuất',
  'profile.edit.fullName': 'Họ và tên',
  'profile.edit.email': 'Email',
  'profile.edit.mobile': 'Số điện thoại',
  'profile.edit.dateOfBirth': 'Ngày sinh',
  'profile.edit.weight': 'Cân nặng',
  'profile.edit.height': 'Chiều cao',
  'profile.edit.submit': 'Cập nhật hồ sơ',
  'profile.edit.success': 'Cập nhật hồ sơ thành công',
  'profile.edit.failure': 'Cập nhật hồ sơ thất bại',
  'profile.favorites.title': 'Yêu thích',
  'profile.favorites.all': 'Tất cả',
  'profile.favorites.video': 'Video',
  'profile.favorites.article': 'Bài viết',
  'profile.favorites.exercises': '{count} Bài tập',
  'profile.privacyPolicy.body':
      'Chúng tôi tôn trọng quyền riêng tư của bạn và cam kết bảo vệ dữ liệu cá nhân của bạn. Nội dung này mô tả cách thông tin của bạn được thu thập, sử dụng và bảo vệ khi bạn dùng FitBody. Để xem chính sách đầy đủ, vui lòng liên hệ đội ngũ hỗ trợ.',
  'profile.settings.title': 'Cài đặt',
  'profile.settings.notification': 'Cài đặt thông báo',
  'profile.settings.password': 'Cài đặt mật khẩu',
  'profile.settings.deleteAccount': 'Xóa tài khoản',
  'profile.settings.deleteConfirm': 'Bạn có chắc chắn muốn xóa tài khoản không? Hành động này không thể hoàn tác.',
  'profile.settings.deleteYes': 'Đồng ý, xóa',
  'profile.notification.general': 'Thông báo chung',
  'profile.notification.sound': 'Âm thanh',
  'profile.notification.doNotDisturb': 'Chế độ không làm phiền',
  'profile.notification.vibrate': 'Rung',
  'profile.notification.lockScreen': 'Màn hình khóa',
  'profile.notification.reminders': 'Nhắc nhở',
  'profile.password.current': 'Mật khẩu hiện tại',
  'profile.password.new': 'Mật khẩu mới',
  'profile.password.confirm': 'Xác nhận mật khẩu mới',
  'profile.password.forgot': 'Quên mật khẩu?',
  'profile.password.change': 'Đổi mật khẩu',
  'profile.password.required': 'Trường này là bắt buộc',
  'profile.password.tooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
  'profile.password.mismatch': 'Mật khẩu mới và xác nhận không khớp',
  'profile.password.success': 'Đổi mật khẩu thành công',
  'profile.password.failure': 'Đổi mật khẩu thất bại',
  'profile.help.title': 'Trợ giúp & Hỏi đáp',
  'profile.help.faqTab': 'Hỏi đáp',
  'profile.help.contactTab': 'Liên hệ',
  'profile.help.general': 'Chung',
  'profile.help.account': 'Tài khoản',
  'profile.help.services': 'Dịch vụ',
  'profile.help.customerService': 'Chăm sóc khách hàng',
  'profile.help.website': 'Website',
  'profile.help.whatsapp': 'Whatsapp',
  'profile.help.facebook': 'Facebook',
  'profile.help.instagram': 'Instagram',
};
