const Map<String, String> workoutStringsEn = {
  'workout.title': 'Workout',
  'workout.tabs.exercises': 'Exercises',
  'workout.tabs.routines': 'Routines',
  'workout.exercise.caloriesPerMinute': '{calories} kcal/min',
  'workout.routine.durationWeeks': '{weeks} weeks',
  'workout.filter.beginner': 'Beginner',
  'workout.filter.intermediate': 'Intermediate',
  'workout.filter.advance': 'Advance',
  'workout.featured.badge': 'Training Of The Day',
  'workout.section.letsGo': "Let's Go {level}",
  'workout.section.generic': 'Workouts',
  'workout.section.subtitle': 'Explore Different Workout Styles',
  'workout.stats.exercises': '{count} Exercises',
  'workout.repetition': 'Repetition {reps}x',
  'workout.round': 'Round {number}',
  'workout.exercise.seconds': '{count} Seconds',
  'workout.exercise.rep': '{count} Rep',
};

const Map<String, String> workoutStringsVi = {
  'workout.title': 'Tập luyện',
  'workout.tabs.exercises': 'Bài tập',
  'workout.tabs.routines': 'Giáo trình',
  'workout.exercise.caloriesPerMinute': '{calories} kcal/phút',
  'workout.routine.durationWeeks': '{weeks} tuần',
  'workout.filter.beginner': 'Mới bắt đầu',
  'workout.filter.intermediate': 'Trung bình',
  'workout.filter.advance': 'Nâng cao',
  'workout.featured.badge': 'Bài Tập Trong Ngày',
  'workout.section.letsGo': 'Bắt Đầu {level}',
  'workout.section.generic': 'Bài Tập',
  'workout.section.subtitle': 'Khám Phá Các Phong Cách Tập Luyện',
  'workout.stats.exercises': '{count} Bài tập',
  'workout.repetition': 'Lặp lại {reps}x',
  'workout.round': 'Vòng {number}',
  'workout.exercise.seconds': '{count} Giây',
  'workout.exercise.rep': '{count} Lần',
};
